version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=amazon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
  
  web-init:
    build: ./Web/web-app
    command: /Web/web-app/Amazon/initweb.sh
    volumes:
      - ./Web/web-app:/Web/web-app
    depends_on:
      - db

  web:
    build: ./Web/web-app
    user: nobody
    volumes:
      - ./Web/web-app:/Web/web-app
    ports:
      - "8000:8000"
    command: /Web/web-app/Amazon/runweb.sh
    depends_on:
    - web-init

  server-init:
    build: ./Server/src
    command: /Server/src/initserver.sh
    volumes:
      - ./Server/src:/Server/src
    depends_on:
      - db

  server:
    build: ./Server/src
    ports:
      - "8080:8080"
    volumes:
      - ./Server/src:/Server/src
    command: /Server/src/runserver.sh
    depends_on:
      - server-init