# Generated by Django 4.1.5 on 2023-04-20 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('dest_addr_x', models.IntegerField(default=0)),
                ('dest_addr_y', models.IntegerField(default=0)),
                ('ups_account', models.CharField(blank=True, max_length=128, null=True)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'open'), (2, 'processing'), (3, 'complete')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128, unique=True)),
                ('price', models.FloatField(default=0.01)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('default_addr_x', models.IntegerField(blank=True, default=0, null=True)),
                ('default_addr_y', models.IntegerField(blank=True, default=0, null=True)),
                ('default_ups_account', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('ware_addr_x', models.IntegerField(default=0)),
                ('ware_addr_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='AmazonWeb.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_num', models.PositiveIntegerField(default=1)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='AmazonWeb.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='AmazonWeb.product')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='AmazonWeb.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'packing'), (2, 'packed'), (3, 'loading'), (4, 'loaded'), (5, 'delivering'), (6, 'delivered')], default=1)),
                ('tracking_num', models.CharField(blank=True, max_length=128, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='AmazonWeb.order')),
                ('truck_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='AmazonWeb.truck')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='AmazonWeb.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='AmazonWeb.user'),
        ),
    ]
