# Generated by Django 4.1.5 on 2023-04-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
    ]
