# Generated by Django 4.1.5 on 2023-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonWeb', '0004_alter_productlist_warehouse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('open', 'open'), ('processing', 'processing'), ('complete', 'complete')], default='open', max_length=128),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('packing', 'packing'), ('packed', 'packed'), ('loading', 'loading'), ('loaded', 'loaded'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='packing', max_length=128),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='truck_status',
            field=models.CharField(choices=[('not_requested', 'not_requested'), ('requested', 'requested'), ('arrived', 'arrived')], default='not_requested', max_length=128),
        ),
    ]
